# Generated by Django 5.0 on 2025-12-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("chatId", models.AutoField(primary_key=True, serialize=False)),
                ("lastMessage", models.TextField(blank=True, null=True)),
                ("lastMessageTime", models.DateTimeField(blank=True, null=True)),
                ("users", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "chats",
                "ordering": ["-lastMessageTime"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("messageId", models.AutoField(primary_key=True, serialize=False)),
                ("chatId", models.IntegerField()),
                ("senderId", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "messages",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("postId", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "mediaType",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=20
                    ),
                ),
                ("mediaURL", models.URLField()),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("userId", models.CharField(max_length=255)),
                ("location", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "posts",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                ("storyId", models.AutoField(primary_key=True, serialize=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("expireAt", models.DateTimeField()),
                (
                    "mediaType",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=20
                    ),
                ),
                ("mediaURL", models.URLField()),
                ("userId", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "stories",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "userId",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("gender", models.CharField(blank=True, max_length=50, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("profilePhoto", models.URLField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("activePincodes", models.JSONField(blank=True, default=list)),
                ("followers", models.JSONField(blank=True, default=list)),
                ("following", models.JSONField(blank=True, default=list)),
                ("idCardUrl", models.URLField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Follower",
            fields=[
                ("documentId", models.AutoField(primary_key=True, serialize=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("followerId", models.CharField(max_length=255)),
                ("followingId", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "followers",
                "unique_together": {("followerId", "followingId")},
            },
        ),
        migrations.CreateModel(
            name="FollowRequest",
            fields=[
                ("documentId", models.AutoField(primary_key=True, serialize=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("fromUserId", models.CharField(max_length=255)),
                ("toUserId", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "followRequests",
                "unique_together": {("fromUserId", "toUserId")},
            },
        ),
    ]
