# Generated by Django 5.0 on 2025-12-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
