# Generated by Django 5.0 on 2025-12-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_otpverification_pendingsignup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingsignup",
            name="device_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="device_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
