# Generated by Django 5.0 on 2025-12-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_pendingsignup_device_id_userprofile_device_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpverification",
            name="session_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
