# Generated by Django 5.0 on 2025-12-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_otpverification_session_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="personal_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="work_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
