# Generated by Django 5.0 on 2026-01-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_userprofile_home_city_userprofile_home_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostComment",
            fields=[
                ("commentId", models.AutoField(primary_key=True, serialize=False)),
                ("postId", models.IntegerField(db_index=True)),
                ("userId", models.CharField(db_index=True, max_length=255)),
                ("content", models.TextField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("parentCommentId", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "post_comments",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="ReportedContent",
            fields=[
                ("reportId", models.AutoField(primary_key=True, serialize=False)),
                ("reporterUserId", models.CharField(db_index=True, max_length=255)),
                (
                    "contentType",
                    models.CharField(
                        choices=[
                            ("post", "Post"),
                            ("user", "User"),
                            ("comment", "Comment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contentId", models.IntegerField(db_index=True)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Reviewed"),
                            ("action_taken", "Action Taken"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "reported_content",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="BlockedUser",
            fields=[
                ("blockId", models.AutoField(primary_key=True, serialize=False)),
                ("blockerUserId", models.CharField(db_index=True, max_length=255)),
                ("blockedUserId", models.CharField(db_index=True, max_length=255)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "blocked_users",
                "ordering": ["-createdAt"],
                "unique_together": {("blockerUserId", "blockedUserId")},
            },
        ),
        migrations.CreateModel(
            name="PostLike",
            fields=[
                ("likeId", models.AutoField(primary_key=True, serialize=False)),
                ("postId", models.IntegerField(db_index=True)),
                ("userId", models.CharField(db_index=True, max_length=255)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "post_likes",
                "ordering": ["-createdAt"],
                "unique_together": {("postId", "userId")},
            },
        ),
        migrations.CreateModel(
            name="PostSave",
            fields=[
                ("saveId", models.AutoField(primary_key=True, serialize=False)),
                ("postId", models.IntegerField(db_index=True)),
                ("userId", models.CharField(db_index=True, max_length=255)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "post_saves",
                "ordering": ["-createdAt"],
                "unique_together": {("postId", "userId")},
            },
        ),
    ]
