# Generated by Django 5.0 on 2026-01-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_postcomment_reportedcontent_blockeduser_postlike_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("post", "Post"),
                    ("question", "Question"),
                    ("alert", "Alert"),
                    ("recommendation", "Recommendation"),
                ],
                default="post",
                max_length=20,
            ),
        ),
    ]
