# Generated by Django 5.0 on 2026-01-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_post_post_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="mediaType",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Video"), ("text", "Text")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="mediaURL",
            field=models.URLField(blank=True, null=True),
        ),
    ]
